### PR TITLE
Fix page render transport.messageHandler missing.

### PR DESCRIPTION
**Pull request by WorldThirteen**
This PR fixes next error:
`TypeError: Cannot read property 'send' of null`

### CODE REVIEW

**Comment by rmhrisk** [comment]
In general is best to stay in sync with the original repo and maintain minimal deltas so we can always merge easily in future. Is is in original repo?

**Comment by WorldThirteen** [comment]
@rmhrisk, no, this is a new code.

**Comment by rmhrisk** [comment]
Should we do PR to PDFjs then?

**Comment by WorldThirteen** [comment]
I think no, this is not the best solution. And I can't normally document this bug, because of random of it reproduce.

**Comment by rmhrisk** [comment]
What is consequence of not merging this then?

**Comment by WorldThirteen** [comment]
Nothing, it is ready to merge.

**Comment by rmhrisk** [comment]
Sorry, I meant we should not merge it if it is not needed.

The more changes we make to this fork the harder it will be to merge in future.

**Pull request merged**
